### ISSUE TITLE
List of TODOs

### ISSUE THREAD

**Issue by nbonacchi** [int-brain-lab/iblrig#364]
List of TODO’s
- 

- [x] Remove flag creation for _iblrig_test_mouse?  #360 
- [ ] Remove iblrig transfer scripts et al from ibllib --> iblrig  #361 
- [ ] Create formal test for raw output footprint of rig configurations  #362
- [ ] Solve ITI drift over session  #363
-
- [x] Verify frame_counter data / actually all columns, formally w/ test
- [x] RAW data loaders for frame data/Create new bin extractor in ibllib
- [ ] Consider changing all Bonsai output files to bin files….
- [ ] Figure out how to run a sequence of tasks indipendently
- [x] make passive a standalone protocol
- [ ] Consider separating the mic recording from the camera workflow and running it w/ no UI
- [ ] Add install env information in videopc and ephyspc
- [x] Define session end ONE calls to try and graceful exit.
- [ ] Change pre and post scripts location from pybpod to main code file
- [ ] raw_data_loaders (rig only uses load_data and load_settings)
- [ ] Deploy spinnaker API to training rigs to upgrade the flycap package (a la ephys rig)
- [ ] Cleanup/Create good object model for users to develop their own tasks
- [x] Harp Photodiode code for substituting frame2ttl

DONE
- [x] Params silent
- [x] Noam's passive session
- [x] Petrina for Friday
- [x] Print contract
- [x] One calls to end even for project, check registration process
- [x] delete asking for project.
- [x] Cyrille Datoviz deplotyment Wed!
- [x] Upgrade deploy spinnaker API videopc
- [x] Iblscripts deploy new bonsai and prepare session procedure... Popup to untrigger?
- [x] CHECK IF EXTRACTOR CAN DEAL WITH _iblrig_*Camera.FrameData.bin
- [x] TRAINING CAMERA WORKFLOW -> NEW bin file for metadata...
- [x] relaunch passive for errored sessions
- [x] RAW data loaders for frame data/Create new bin extractor in ibllib
- [x] Verify frame_counter data / actually all columns, formally w/ test

---FROZEN RC---

- [x] update repo procedure from update calling... (not sure it will fix the update of the update)
- [x] Exposed rate of passive stimulation workflow
- [x] RFM_StimRate workflow, fix extensions after exposing rate
- [x] Transfer of video data from ephysRig running training (ines)  # on ibllib/develop

ONGOING:

- [ ] Remove iblrig transfer scripts et al from ibllib -> iblrig
- [ ] Write critical QC on raw data
- [x] Finish pbpod_config module to support CLI for fetching subjects/projects/etc...
- [ ] Deploy spinnaker API to training rigs to upgrade the flycap package (a la ephys rig)
- [ ] Consider changing all Bonsai output files to bin files… int-brain-lab/iblenv#237
- [ ] Change pre and post scripts location from pybpod to main code file
- [ ] Consider separating the mic recording from the camera workflow and running it w/ no UI
- [x] Add install env information in videopc and ephyspc
- [x] Define session end ONE calls to try and graceful exit.
- [ ] raw_data_loaders (rig only uses load_data and load_settings)
- [ ] Create raw data loaders/test raw output footprint
- [ ] Cleanup/Create good object model for users to develop their own tasks
- [x] Project management for U19 + personal projects
- [ ] Enhancement for water calibration low priority --> int-brain-lab/iblenv#116
