### ISSUE TITLE
Integrate UDP message server into iblrig

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/iblrig#642]
This could allow us to manage auxiliary acquisition devices and thus reduce session ID mismatches.

- [x] Use threading to run services within synchronous code
- [x] Set up auxiliary init and start procedures
- [ ] [Handle IO errors within thread](https://github.com/int-brain-lab/iblrig/issues/682)
- [x] Create mixin in iblrig
- [x] Add client part to video pc script
- [x] Add client part to ephys pc script
- [x] Add procedure to determine remote main sync and fetch exp ref from this PC
- [ ] [Mixin iblrig tests](https://github.com/int-brain-lab/iblrig/issues/684)
- [x] Support transfer of Alyx token
- [x] Set up auxiliary stop and cleanup procedures
- [ ] [Add remote devices back into GUI](https://github.com/int-brain-lab/iblrig/issues/683)
- [x] Integrate with timeline on MATLAB
- [x] Integrate with ScanImage rig
- [x] Permit services to send messages without awaiting response
